export const STATUS_LOADING = 'STATUS_LOADING';
export const STATUS_READY = 'STATUS_READY';
export const STATUS_PLAYING = 'STATUS_PLAYING';
export const STATUS_FINISHED = 'STATUS_FINISHED';
export const STATUS_SCORE_CHECK = 'STATUS_SCORE_CHECK';
export const STATUS_SCORE_SUBMIT = 'STATUS_SCORE_SUBMIT';
export const STATUS_SCORE_NOT_SUBMIT = 'STATUS_SCORE_NOT_SUBMIT';